# docker compose file
# each container shares a Docker volume backend_volume
# for each container, we have bind mounts for the
# corresponding code for development stage
version: "3.7"
services: 
  backend_server:
    build: ./backend_server
    volumes: 
     - ./backend_server:/backend_server
     - backend_volume:/data
    ports:
      - 5000:5000
  backend_coling:
    build: ./backend_coling
    volumes: 
     - ./backend_coling:/backend_coling
     - backend_volume:/data
    
  backend_fairseq:
    build: ./backend_fairseq
    volumes:
     - ./backend_fairseq:/backend_fairseq
     - backend_volume:/data
volumes: 
  backend_volume:

  
    
  
# run with --build if you change Dockerfile